### ISSUE TITLE
isctl apply -f doesn't work for bulk.MoCloners

### ISSUE THREAD

**Issue by baelen-git** [cgascoig/isctl#127]
It will throw this error

```
jump@jumpserver:~/intersight$ ./isctl apply -f serverprofiles.yaml
FATA[0000] Unable to determine order to apply MOs: unable to get update operation for ClassID: bulk.MoCloner
```

The file I'm trying to apply is
```yaml
ClassId: bulk.MoCloner
Organization: default
Sources: MoRef:ServerProfileTemplateRelationship[OCP-BM]
Targets:
- Name: OCP-BM-1
  ObjectType: server.Profile
  Organization: default
  Description: ''
  Tags: []
  ServerPool: MoRef:ResourcePoolPoolRelationship[OCP-BM]
  ServerAssignmentMode: Pool
- Name: OCP-BM-2
  ObjectType: server.Profile
  Organization: default
  Description: ''
  Tags: []
  ServerPool: MoRef:ResourcePoolPoolRelationship[OCP-BM]
  ServerAssignmentMode: Pool
```

I think the reason is tha the bulk.MoCloners only supports POST, no PATCH or  GET
