### ISSUE TITLE
Support delete for MO's without Name attribute in isctl apply -d -f

### ISSUE THREAD

**Issue by baelen-git** [cgascoig/isctl#147]
For example, the fabric.PortMode API doesn't have a Name attribute.
 
I'm using the following yaml file which i can apply without issues 
```yaml
ClassId: fabric.PortPolicy
Description: ""
DeviceModel: UCS-FI-6454
Name: 6465-lab-ports
Organization: LAB-RESOURCES
---
ClassId: fabric.PortMode
PortPolicy: MoRef:fabric.PortPolicy[6465-lab-ports]
PortIdStart: 1
PortIdEnd: 4
SlotId: 1
```

Yet when I try to delete it it I will receive the following error
```
❯ isctl apply -d -f portpolicy.yaml 
FATA[0000] Error while destroying MOs: invalid MO - no Name attribute 
```

Excepted behavior is to just continue when you can't delete an object that doesn't have a Name attribute.
For example this fabric.PortMode MO will automatically be deleted in the backend when I delete the fabric.PortPolicy that it's linked to.
