### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by baelen-git** [cgascoig/isctl#148]
When running 

isctl apply -f 3_serverProfileTemplate.yaml

which contains

```yaml
ClassId: server.ProfileTemplate
Name: IMM-RHEL
Organization: IMM-Troubleshooting
#settings
TargetPlatform: FIAttached
PolicyBucket:
  - MoRef:BiosPolicyRelationship[IMM-BIOS]
  - MoRef:BootPrecisionPolicyRelationship[IMM-Boot]
  - MoRef:IpmioverlanPolicyRelationship[IMM-IPMI-off]
  - MoRef:KvmPolicyRelationship[IMM-TunneledKVM
  - MoRef:SolPolicyRelationship[IMM-SOL
  - MoRef:StorageStoragePolicyRelationship[IMM-M.2]
  - MoRef:VnicLanConnectivityPolicyRelationship[IMM-LAN]
  - MoRef:AccessPolicyRelationship[IMM-IMC-INBAND]
  - MoRef:PowerPolicyRelationship[IMM-Power]
#  - MoRef:SdcardPolicyRelationship[utilityCard]
```
