### ISSUE TITLE
MoRef syntax needs to be expanded to support organisations

### ISSUE THREAD

**Issue by cgascoig** [cgascoig/isctl#151]
subsequently when I try to create an EndPointUserRole that refers a an EndPointUser that has a name which exists in multiple orgs I also get the error:

FATA[0000] Error while applying MOs: error setting up operation body: GetMoMoRef: unable to get moid 

```yaml
ClassId: iam.EndPointUserRole
Enabled: true
EndPointRole: #This MoRef is static because there are multiple system defined Roles with the name admin
- ClassId: mo.MoRef
  Moid: 59684dcb5e468000016525c8
EndPointUser: MoRef:iam.EndPointUser[boris]
EndPointUserPolicy: MoRef:iam.EndPointUserPolicy[IMM-LocalAdmin]
Password: hahahajajaja
```

_Originally posted by @baelen-git in https://github.com/cgascoig/isctl/issues/149#issuecomment-2090508070_
