### ISSUE TITLE
Support Type based lookup for iam.EndPointRole

### ISSUE THREAD

**Issue by baelen-git** [cgascoig/isctl#155]
These are system default roles which are not in an organization.
There are multiple with the same name and the only difference is the Type,therefor I would like to do something like this
```
MoRef[Type=IMC\admin]
```
Or whatever syntax you prefer, I think you get the idea :) 

This would be used in the following example

```yaml
ClassId: iam.EndPointUserRole
Enabled: true
EndPointRole: MoRef[Type=IMC\admin]
EndPointUser: MoRef[LAB-RESOURCES\admin]
EndPointUserPolicy: MoRef[LAB-RESOURCES\IMM-LocalAdmin]
Password: hahahahajaja
---
ClassId: iam.EndPointUser
Organization: LAB-RESOURCES
Name: admin
---
ClassId: iam.EndPointUserPolicy
Organization: LAB-RESOURCES
Name: IMM-LocalAdmin
PasswordProperties:
  ClassId: iam.EndPointPasswordProperties
  EnablePasswordExpiry: false
  EnforceStrongPassword: true
  ForceSendPassword: false
  GracePeriod: 0
  NotificationPeriod: 15
  PasswordExpiryDuration: 90
  PasswordHistory: 0
```
