### ISSUE TITLE
New MO's created instead of updated with batch operations for certain MO's

### ISSUE THREAD

**Issue by baelen-git** [cgascoig/isctl#158]
For example with the vnic.EthIf
This works fine when I execute the code for the first time

```yaml
ClassId: vnic.EthIf
Name: mgmt
#settings
FailoverEnabled: true
EthAdapterPolicy: MoRef[LAB-RESOURCES\IMM-Linux]
EthNetworkPolicy: MoRef[LAB-RESOURCES\IMM-Trunk]
EthQosPolicy: MoRef[LAB-RESOURCES\IMM-QOS]
FabricEthNetworkControlPolicy: MoRef[LAB-RESOURCES\IMM-LLDP]
FabricEthNetworkGroupPolicy: 
  - MoRef[LAB-RESOURCES\IMM-MGMT]
LanConnectivityPolicy: MoRef[LAB-RESOURCES\IMM-LAN]
MacPool: MoRef[LAB-RESOURCES\IMM-MAC]
MacAddressType: "POOL"
Order: 0
Placement:
  ClassId: vnic.PlacementSettings
  AutoSlotId: true
  SwitchId: A
```

However when I try to run it a second time I will receive this error

```
INFO[0024] Performing create operation on new MO (Name: mgmt, ClassId: vnic.EthIf) 
FATA[0027] Error while applying MOs: error executing operation: request failed: 400 Bad Request: Cannot configure same 'mgmt' name on multiple Virtual Ethernet Interfaces 
```

It shows that it wants to create the same MO again, however it already exists on the vNIC.

**Comment by baelen-git** [comment]
I'm seeing the same behavior with other MO's, for example
fabric.Vlan
fabric.SwitchProfile
fabric.PortMode

These are all nested policies and don't seem to have an organization attached to them, but they always belong to another policy.

However when I apply this fabric.Vlan code
```yaml
ClassId: fabric.Vlan
Name: VLAN_70_A
#settings
EthNetworkPolicy: MoRef[LAB-RESOURCES\IMM-VLANS-A]
MulticastPolicy: MoRef[LAB-RESOURCES\IMM-Multicast]
VlanId: 70
AutoAllowOnUplinks: true
IsNative: false
PrimaryVlanId: 0
SharingType: None
```

Everytime I run it it will create a new VLAN_70_A with the same name and the same settings.
the Policy is smart enough to detect this as only 1 VLAN and clean up all attached VLANs when deleting, however we should not do a create but an update.

I can understand this is difficult when we support MO's with the same name in the same org.... 
Or MO's where we don't even have a Name property (fabric.UplinkRole)

**Comment by baelen-git** [comment]
You can get the right unique identifiers for each MO from meta.Definition
Could we leverage this for deciding when to update an MO instead of creating one?

```
❯ isctl get meta definition --filter "Name eq 'fabric.PortMode'" --select IdentityConstraints
- ClassId: meta.Definition
  IdentityConstraints:
  - ClassId: meta.IdentityDefinition
    Fields:
    - SlotId
    - PortIdStart
    - PortIdEnd
    - PortPolicy
    ObjectType: meta.IdentityDefinition
  Moid: 663452406f6269330170460d
  ObjectType: meta.Definition 
```

**Comment by baelen-git** [comment]
Same issue, different MO

code
```yaml
ClassId: resource.Group
Name: IMM-Troubleshooting
#settings
Selectors:
- ClassId: resource.Selector
  Selector: /api/v1/asset/DeviceRegistrations?$filter=Moid in('<redacted-moid>')
```

First apply works.
Second apply tries to create it again with this error

```
❯ isctl apply -f 1_orgs.yaml  
INFO[0001] Performing create operation on new MO (Name: IMM-Troubleshooting, ClassId: resource.Group) 
FATA[0001] Error while applying MOs: error executing operation: request failed: 400 Bad Request: Cannot create or modify the object. A managed object with the same identifying criteria already exists. 
```
