### ISSUE TITLE
PANIC error when using names with a space in MoRef

### ISSUE THREAD

**Issue by baelen-git** [cgascoig/isctl#163]
Code

```yaml
ClassId: iam.Permission
Name: IMM-Lab-User
---
ClassId: iam.ResourceRoles
Permission: MoRef[IMM-Lab-User]
Resource: MoRef:organization.Organization[IMM-Troubleshooting]
Roles: 
- MoRef[Server Administrator]
- MoRef[UCS Domain Administrator]
- MoRef[Workflow Designer]
```

Throws this error
```
panic: runtime error: invalid memory address or nil pointer dereference
```

But this will work
```yaml
Roles: 
- MoRef[$filter:Name eq 'Server Administrator']
- MoRef[$filter:Name eq 'UCS Domain Administrator']
- MoRef[$filter:Name eq 'Workflow Designer']
```
