### ISSUE TITLE
MoRef not working for intersight.FabricEthNetworkGroupPolicyRelationship

### ISSUE THREAD

**Issue by baelen-git** [cgascoig/isctl#96]
Try to apply

```
ClassId: vnic.EthIf
Name: eth0
FailoverEnabled: false
EthAdapterPolicy: MoRef[Linux-Adapters]
EthNetworkPolicy: MoRef[TrunkMode]
EthQosPolicy: MoRef[noQOS]
FabricEthNetworkControlPolicy: MoRef[lldpOn]
FabricEthNetworkGroupPolicy: MoRef[network-group]
LanConnectivityPolicy: MoRef[Dual-vNICs]
MacPool: MoRef[default-macpool]
Order: 0
Placement:
  ClassId: vnic.PlacementSettings
  AutoPciLink: true
  AutoSlotId: true
  Uplink: 0
  SwitchId: A
```

you will get an like
FATA[0004] Error while applying MOs: Error setting up operation body: SetBodyParams: Error unmarshalling JSON: json: cannot unmarshal string into Go struct field VnicEthIfWithoutEmbeddedStruct.FabricEthNetworkGroupPolicy of type []intersight.FabricEthNetworkGroupPolicyRelationship

Eventhough the FabricEthNetworkGroupPolicy that I'm referencing exists

**Comment by cgascoig** [comment]
`FabricEthNetworkGroupPolicy` should be a list of references:

```yaml
ClassId: vnic.EthIf
Name: eth0
FailoverEnabled: false
EthAdapterPolicy: MoRef[Linux-Adapters]
EthNetworkPolicy: MoRef[TrunkMode]
EthQosPolicy: MoRef[noQOS]
FabricEthNetworkControlPolicy: MoRef[lldpOn]
FabricEthNetworkGroupPolicy: 
 - MoRef[network-group]
LanConnectivityPolicy: MoRef[Dual-vNICs]
MacPool: MoRef[default-macpool]
Order: 0
Placement:
  ClassId: vnic.PlacementSettings
  AutoPciLink: true
  AutoSlotId: true
  Uplink: 0
  SwitchId: A
```

Feel free to reopen this issue if that doesn't fix the problem
